### PR TITLE
Update ogre_slice.h

### PR DESCRIPTION
**Pull request by XuHaiwang**
Add three head files. Fix the error during compiling in Arch Linux.

### CODE REVIEW

**Comment by cschuet** [comment]
@XuHaiwang Thanks for the PR. Is it not sufficient to add these headers to the .cc?

**Comment by cschuet** [comment]
@XuHaiwang Friendly ping.

**Comment by XuHaiwang** [comment]
hi, it is better that these headers exist in ogre_slice.h because of the GCC version in Arch Linux.

**Comment by ojura** [comment]
Can you add more details? Which GCC version, what symbols are used in ogre_slice.h which are found in these headers?

**Pull request closed without merging**
