### PR TITLE
Add submap orgins to viz marker script

### PR DESCRIPTION
**Pull request by jihoonl**
To visualize origin of submaps in rviz. It would be nicer if we can integrate this in `cartographer_rviz` plugin later.

submap_pose

### CODE REVIEW

**Comment by SirVer** [comment]
Why not do this in c++ in the rViz plugin? You could add a dot in the place of the origin.

**Comment by jihoonl** [comment]
Yeah. I agree that it would be better to do this in rviz plugin. It is a simple workaround before implementing it in `cartographer_rviz`.  I opened this PR with the current script based approach because I don't know when I will spend a time to implement this feature in cartographer_rviz plugin.

**Comment by SirVer** [comment]
Glad that we agree that the rViz plugin is the right place for this. I will close this pull request then, since it seems this forks the responsibilities of the rViz plugin and therefore muddies responsibilities.  @jihoonl You cool with that?

I opened #404 to track the c++ implementation.

**Comment by jihoonl** [comment]
Yup. I am fine with it. :wink:

**Pull request closed without merging**
