### PR TITLE
 Start a new trajectory with an initial pose from /initalpose topic for compatibility for ROS api in purelocalization mode

### PR DESCRIPTION
**Pull request by doisyg**
Quick and dirty implementation
To be started after a pure localization node.
Assumes that the map trajectory ID is 0 and that the `geometry_msgs/PoseWithCovarianceStamped` received on the `/intialpose topic` is in the `map` frame

### CODE REVIEW

**Comment by doisyg** [comment]
I signed it!

**Comment by ojura** [comment]
Why not extend the existing `start_trajectory` executable?

**Comment by ojura** [comment]
I agree, do open an RFC. I think this would be useful to have.

**Comment by jihoonl** [comment]
I third for RFC. It is a necessary feature and I had my own version too in our internal branch. I would love to add my input.

**Comment by doisyg** [comment]
Ok, I will try to write a RFC this week.

**Comment by cschuet** [comment]
I am closing this PR for now. Let's reopen it when we have agreed upon the RFC.

**Comment by doisyg** [comment]
RFC draft submitted: https://github.com/googlecartographer/rfcs/pull/17
Please feel free to improve, comment, discuss...

**Comment by zeynepustun** [comment]
Hello,
  I have tried to run @doisyg implementation for setting trajectory initial pose from RVIZ.
  I have built the code  and ran cartographer_start_trajectory_initial_pose successfully.

1. roslaunch cartographer_ros demo_backpack_2d_localization.launch    load_state_filename:=/home/largo/carto_ws/localization/b2-2016-04-05-14-44-52.bag.pbstream
    
 I ran this code. In demo_backpack_2d_localization.launch I added start_trajectory_with_default_topics=false so it does not create a new trajectory.
   
2. ./cartographer_start_trajectory_initial_pose
    This node subscribes to /initialpose topic

3.I set the initial pose from RVIZ.

I get error E0619 16:12:20.816743 16921 node.cc:461] Trajectory 1 is not created yet.
[ERROR] [1560949940.817069473]: E0619 16:12:20.000000 16921 node.cc:461] Trajectory 1 is not created yet.

Any help appreciated..

**Comment by wesigj** [comment]
that code is too old, it is disable for the latest version, baceuse i can not compile it.

**Pull request closed without merging**
