### PR TITLE
Follow googlecartographer/cartographer#599

### PR DESCRIPTION
**Pull request by jihoonl**
Use submap_painter. Merge this after googlecartographer/cartographer#599.

### CODE REVIEW

**Comment by SirVer** [comment]
This also says "Abuse detected" on travis, so needs to be reopened.

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Error: exit status 128

Log: => Rebasing PR 561 on googlecartographer/cartographer_ros onto master.
=> Switching to branch master.
 $ git checkout -f [data/cartographer_ros]
Your branch is up to date with 'origin/master'.
 $ git clean -fd [data/cartographer_ros]
 $ git checkout master [data/cartographer_ros]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer_ros]
Already up to date.
 $ git remote add magazino git@github.com:magazino/cartographer_ros.git [data/cartographer_ros]
 $ git fetch magazino [data/cartographer_ros]
From github.com:magazino/cartographer_ros
 * [new branch]      cmakelist_fixes        -> magazino/cmakelist_fixes
 * [new branch]      constraints_visualization -> magazino/constraints_visualization
 * [new branch]      finish_trajectory      -> magazino/finish_trajectory
 * [new branch]      initialpose_topic      -> magazino/initialpose_topic
 * [new branch]      master                 -> magazino/master
 * [new branch]      occ_exporter           -> magazino/occ_exporter
 * [new branch]      occpancy_exporter      -> magazino/occpancy_exporter
 * [new branch]      resolve_topic_name     -> magazino/resolve_topic_name
 * [new branch]      submap_id_text         -> magazino/submap_id_text
 * [new branch]      submap_painter_oc_node -> magazino/submap_painter_oc_node
 $ git branch --track pr_561 magazino/submap_painter_oc_node [data/cartographer_ros]
Branch 'pr_561' set up to track remote branch 'submap_painter_oc_node' from 'magazino'.
=> Switching to branch pr_561.
 $ git checkout -f [data/cartographer_ros]
Your branch is up to date with 'origin/master'.
 $ git clean -fd [data/cartographer_ros]
 $ git checkout pr_561 [data/cartographer_ros]
Switched to branch 'pr_561'
Your branch is up to date with 'magazino/submap_painter_oc_node'.
 $ git pull --force [data/cartographer_ros]
Already up to date.
 $ git rebase master [data/cartographer_ros]
First, rewinding head to replay your work on top of it...
Applying: use submap painter
Using index info to reconstruct a base tree...
M	cartographer_ros/cartographer_ros/occupancy_grid_node_main.cc
Falling back to patching base and 3-way merge...
Auto-merging cartographer_ros/cartographer_ros/occupancy_grid_node_main.cc
Applying: address reviewer's comment from googlecartographer/cartographer#599
error: Failed to merge in the changes.
Using index info to reconstruct a base tree...
M	cartographer_ros/cartographer_ros/occupancy_grid_node_main.cc
Falling back to patching base and 3-way merge...
Auto-merging cartographer_ros/cartographer_ros/occupancy_grid_node_main.cc
CONFLICT (content): Merge conflict in cartographer_ros/cartographer_ros/occupancy_grid_node_main.cc
Patch failed at 0002 address reviewer's comment from googlecartographer/cartographer#599
The copy of the patch that failed is found in: .git/rebase-apply/patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

=> Abandoning branch pr_561.
=> Switching to branch master.
 $ git checkout -f [data/cartographer_ros]
 $ git clean -fd [data/cartographer_ros]
 $ git checkout master [data/cartographer_ros]
Warning: you are leaving 1 commit behind, not connected to
any of your branches:

  12f6a15 use submap painter

If you want to keep it by creating a new branch, this may be a good time
to do so with:

 git branch <new-branch-name> 12f6a15

Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_561 [data/cartographer_ros]
Deleted branch pr_561 (was 3d5c8c8).

**Comment by SirVer** [comment]
I fixed the merge conflicts.

@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Error: exit status 1

Log:
~~~
=> Rebasing PR 561 on googlecartographer/cartographer_ros onto master.
=> Switching to branch master.
 $ git checkout -f [data/cartographer_ros]
Your branch is up to date with 'origin/master'.
 $ git clean -fd [data/cartographer_ros]
 $ git checkout master [data/cartographer_ros]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer_ros]
Already up to date.
 $ git remote add magazino git@github.com:magazino/cartographer_ros.git [data/cartographer_ros]
fatal: remote magazino already exists.
 $ git fetch magazino [data/cartographer_ros]
From github.com:magazino/cartographer_ros
 + 3d5c8c8...f93f834 submap_painter_oc_node -> magazino/submap_painter_oc_node  (forced update)
 $ git branch --track pr_561 magazino/submap_painter_oc_node [data/cartographer_ros]
Branch 'pr_561' set up to track remote branch 'submap_painter_oc_node' from 'magazino'.
=> Switching to branch pr_561.
 $ git checkout -f [data/cartographer_ros]
Your branch is up to date with 'origin/master'.
 $ git clean -fd [data/cartographer_ros]
 $ git checkout pr_561 [data/cartographer_ros]
Switched to branch 'pr_561'
Your branch is up to date with 'magazino/submap_painter_oc_node'.
 $ git pull --force [data/cartographer_ros]
Already up to date.
 $ git rebase master [data/cartographer_ros]

It seems that there is already a rebase-apply directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr "/usr/local/google/home/hrapp/prog/go/data/cartographer_ros/.git/rebase-apply"
and run me again.  I am stopping in case you still have something
valuable there.
=> Abandoning branch pr_561.
=> Switching to branch master.
 $ git checkout -f [data/cartographer_ros]
Your branch is up to date with 'magazino/submap_painter_oc_node'.
 $ git clean -fd [data/cartographer_ros]
 $ git checkout master [data/cartographer_ros]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_561 [data/cartographer_ros]
Deleted branch pr_561 (was f93f834).

~~~

**Comment by wally-the-cartographer** [comment]
Error: exit status 128

Log:
~~~
=> Rebasing PR 561 on googlecartographer/cartographer_ros onto master.
=> Switching to branch master.
 $ git rebase --abort [data/cartographer_ros]
No rebase in progress?
 $ git checkout -f [data/cartographer_ros]
 $ git clean -fd [data/cartographer_ros]
 $ git checkout master [data/cartographer_ros]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer_ros]
Already up to date.
 $ git remote add magazino git@github.com:magazino/cartographer_ros.git [data/cartographer_ros]
fatal: remote magazino already exists.
 $ git fetch magazino [data/cartographer_ros]
 $ git branch --track pr_561 magazino/submap_painter_oc_node [data/cartographer_ros]
fatal: A branch named 'pr_561' already exists.
=> Abandoning branch pr_561.
=> Switching to branch master.
 $ git rebase --abort [data/cartographer_ros]
No rebase in progress?
 $ git checkout -f [data/cartographer_ros]
Your branch is up to date with 'origin/master'.
 $ git clean -fd [data/cartographer_ros]
 $ git checkout master [data/cartographer_ros]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_561 [data/cartographer_ros]
Deleted branch pr_561 (was 3d5c8c8).

~~~

**Pull request merged**
