### PR TITLE
Enable publishing all bag messages in offline node

### PR DESCRIPTION
**Pull request by ojura**
This introduces an option called 'publish_all_bag_messages' which publishes everything from the bag as the offline node processes it. For example, if there is a camera on the robot, the images from the camera topic can be watched if the option is enabled, since the offline node will publish all messages from the bag (just like rosbag play).

### CODE REVIEW

**Comment by ojura** [comment]
@pifon2a What happened? :-) You force pushed master to this branch.

**Comment by gaschler** [comment]
@ojura Thanks for reporting. We are on it, the formatting bot make a mistake.

**Comment by pifon2a** [comment]
Wally happened. This is our wonderful merge bot for git. It runs on my machine and uses my account to break stuff. :)

**Comment by ojura** [comment]
@cschuet @gaschler ping for a review

**Comment by cschuet** [comment]
@gaschler @ojura I agree with Andre's sentiment. I don't see this as generally useful enough to offset the cost of maintaining the code. As always thanks for putting in the effort and inventiveness to come up with new feature ideas, but I don't this is something that should go into master.

**Comment by ojura** [comment]
Okay. I have no strong feelings about this - it was an one-off thing which was useful to me at some point when doing some debugging, so I tried to get it merged in hope it would be useful to someone else at some point. I see why you think maintaining this feature one is going to be difficult given the direction Cartographer development is taking (grpc and cloud slam). However, I think that the offline node _is_ trying to reimplement rosbag play in a certain kind of way.

I will rebase the other PR (the time skip option) not to be dependent on this one. Unlike this one, I think that feature is really useful, and requires minimal interventions in code.

**Pull request closed without merging**
