### PR TITLE
Do not include trimmed submaps into the occupancy grid

### PR DESCRIPTION
**Pull request by MichaelGrupp**
Derive submap IDs that don't appear in the submap list anymore and delete the corresponding slices from our state before drawing.

### CODE REVIEW

**Comment by MichaelGrupp** [comment]
Hey, I'm new to the Magazino Cartographer team - the CLA should be signed now :relaxed:

**Comment by SirVer** [comment]
@MichaelGrupp welcome! Thanks for the contribution, very straightforward and easy to understand.

I reworded the commit message a bit, otherwise lgtm.

**Comment by SirVer** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user SirVer. Merge queue now has a length of 1.

**Pull request merged**
