### PR TITLE
Use timing channel from PointCloud2, if available.

### PR DESCRIPTION
**Pull request by ojura**
Related to #772. Replaces #773.

### CODE REVIEW

**Comment by cschuet** [comment]
@gaschler Can you review this?

**Comment by gaschler** [comment]
I generally like the feature, but as I said, I would like to see one public example bag file that actually uses it so I can verify before it can be merged. @ojura Do you have an example bag file that you can share publicly?

**Comment by ojura** [comment]
Okay, wonderful. I'll try to prepare a bag for you sometime this week.

**Comment by gaschler** [comment]
I'm closing this for now, please let me know when test data is available.

**Comment by ojura** [comment]
Sorry about that, I was swamped. I'll submit a couple of datasets so you can try it out.

**Comment by ojura** [comment]
@gaschler I am uploading a couple of datasets for you to try out with this branch, here:

https://1drv.ms/f/s!AktUrV_lPTr9jjvzs3V9ySAMtavl

**Comment by gaschler** [comment]
Cool, I'll take a look. (I cannot reopen this PR because it "was force-pushed or recreated".) Feel free to open a new one and I'll review.
Did you record the data yourself or is it converted from a public dataset?

**Comment by gaschler** [comment]
> I0611 18:56:45.815140 233192 rosbag_validate_main.cc:398] Time delta histogram for consecutive messages on topic "imu" (frame_id: "imu"):
Count: 29953  Min: 0.005000  Max: 0.005000  Mean: 0.005000

IMU timestamps seem very accurate in this bag file ;-)

**Pull request closed without merging**
