### PR TITLE
Internal cleanup.

### PR DESCRIPTION
**Pull request by zjwoody**
Fix lint error.

### CODE REVIEW

**Comment by zjwoody** [comment]
I see, 
how about change all the header guards with double "CARTOGRAPHER_ROS", since the files are all under path cartographer_ros/cartographer_ros/... ?

**Comment by gaschler** [comment]
@cschuet, what do you think about making all include guards longer? I think this is low priority but I'm not opposed.

**Comment by cschuet** [comment]
@zjwoody @gaschler Why is this change necessary? Why don't the other header files generate a linter error?

**Comment by zjwoody** [comment]
The third party header guard is not google style, if it's length > 80 characters it won't pass is_header_guard check, so I have to change it to google style for long header guard. Most of the files don't have long header guard, so they won't generate the lint error. 
I think it will be more consistency to change all the header guard by the path which obey the google style.

**Comment by zjwoody** [comment]
Hi @gaschler , I modified all the header guards in cartographer_ros, thanks for the review!

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Pull request merged**
