### PR TITLE
Add a script for testing with fake landmarks to scripts/dev

### PR DESCRIPTION
**Pull request by MichaelGrupp**
See `./publish_fake_random_landmarks.py --help` for documentation.

### CODE REVIEW

**Comment by MichaelGrupp** [comment]
Ran `yapf -i --style=chromium` to be consistent with the other Python files. They are in Chromium style for some reason.

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by pifon2a** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user pifon2a. Merge queue now has a length of 1.

**Pull request merged**
