### PR TITLE
Deduplicate loading options for offline node

### PR DESCRIPTION
**Pull request by ojura**
This is preparation for #636. 

I noticed that there is duplicated code for loading options for the offline and GRPC offline node because they are needed while constructing the map builder for the non-GRPC offline node (and that step is the only difference between the offline node and the GRPC offline node).

I got around this by passing a map builder factory to `RunOfflineNode` instead, so we can deduplicate the code for loading options by doing it inside `RunOfflineNode`.

### CODE REVIEW

**Comment by ojura** [comment]
@cshuet PTAL so I can continue rebasing #636.

**Comment by ojura** [comment]
@cschuet ping :)

**Comment by cschuet** [comment]
@ojura Sorry again! Tomorrow! Really!

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by cschuet** [comment]
@ojura  Thanks!

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Pull request merged**
