### PR TITLE
HandleRangefinder time refers to newest point.

### PR DESCRIPTION
**Pull request by gaschler**
This is necessary so that sensor::Collator queues range data
after previous odometry and IMU data, and LocalTrajectoryBuilder
will be able to unwarp each point.

### CODE REVIEW

**Comment by gaschler** [comment]
This PR has some history in https://github.com/googlecartographer/cartographer_ros/pull/576 that had to be abandoned because a merge bot issue.

**Comment by gaschler** [comment]
@cschuet PTAL

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 1.

**Pull request merged**
