### PR TITLE
List files explicitly in cartographer_ros_msgs/CMakeLists.txt

### PR DESCRIPTION
**Pull request by MichaelGrupp**
`DIRECTORY` by itself doesn't work as reliable as expected.

### CODE REVIEW

**Comment by ojura** [comment]
How did you run into this?

**Comment by MichaelGrupp** [comment]
I think it's problematic if you have an existing build space, add a new msg file and re-build without reconfiguring CMake.

**Comment by gaschler** [comment]
> How did you run into this?

The ROS Buildfarm build failed.

**Comment by MichaelGrupp** [comment]
http://build.ros.org/job/Ldoc__cartographer_ros__ubuntu_xenial_amd64/20/

**Comment by MichaelGrupp** [comment]
@gaschler was faster :)

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 2.

**Pull request merged**
