### PR TITLE
Add pbstream_map_publisher_main.cc

### PR DESCRIPTION
**Pull request by MichaelGrupp**
Implements [RFC 06](https://github.com/googlecartographer/rfcs/blob/master/text/0006-serve-ros-map-from-pbstream.md)

### CODE REVIEW

**Comment by MichaelGrupp** [comment]
Finishes the work for this RFC started by @jihoonl with https://github.com/googlecartographer/cartographer_ros/pull/633 and https://github.com/googlecartographer/cartographer/pull/782

**Comment by MichaelGrupp** [comment]
@wally-the-cartographer are you alright?

**Comment by MichaelGrupp** [comment]
```
$ git show 7603183c86021e0fb660b33d76cb7550340dda20

commit 7603183c86021e0fb660b33d76cb7550340dda20
Merge: 92b1ce1 5cd81be
Author: Alexander Belyaev <32522095+pifon2a@users.noreply.github.com>
Date:   Wed Feb 7 18:11:53 2018 +0100

    Merge branch 'master' into serve-ros-map-from-pbstream
```

I guess he's complaining because of this mail. Can you edit the commiter e-mail in this one?

**Comment by pifon2a** [comment]
Could you please, revert this commit (7603183c86021e0fb660b33d76cb7550340dda20) then, it should work?

**Comment by MichaelGrupp** [comment]
`git commit --amend --author="Alexander Belyaev <pifon@google.com>"` did the job.

**Comment by pifon2a** [comment]
Nice, sorry for this.

**Comment by MichaelGrupp** [comment]
No problem :D

**Comment by jihoonl** [comment]
@MichaelGrupp thank you for finishing this. I couldn't find the time to implement it feature recently.

One comment. You may want to refactor [occupancy_grid_node_main.cc:171-204] to use CreateOccupancyGridMsg as well.

**Comment by MichaelGrupp** [comment]
Thanks for the hint, @jihoonl, will do that once this is merged.

**Comment by MichaelGrupp** [comment]
Trigger Wally?

**Pull request merged**
