### PR TITLE
HandleRangefinder time refers to newest point.

### PR DESCRIPTION
**Pull request by gaschler**
This is necessary so that sensor::Collator queues range data
after previous odometry and IMU data, and LocalTrajectoryBuilder
will be able to unwarp each point.

### CODE REVIEW

**Comment by gaschler** [comment]
I uploaded all the corrections that time for PointCloud refers to when the last point was acquired, please take another look.

**Comment by SirVer** [comment]
@gaschler This cannot be merged before https://github.com/googlecartographer/cartographer/pull/636, right?

**Comment by gaschler** [comment]
Technically it could be merged, but I haven't evaluated how quality changes when the timestamp is no longer in the middle of the measurement. So I'll close this until  https://github.com/googlecartographer/cartographer/pull/636 is in reach.

**Comment by gaschler** [comment]
Because the merge bot did something wrong, the CLA flag became false, which is not recoverable. Closing this PR and opening a new one.

**Pull request closed without merging**
