### PR TITLE
Add cartographer_dev_rosbag_publisher

### PR DESCRIPTION
**Pull request by gaschler**
This adds a tool to publish a bag file without publishing a simulated clock, modifying header timestamps.

### CODE REVIEW

**Comment by pifon2a** [comment]
@wally-the-cartographer  merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user pifon2a. Merge queue now has a length of 1.

**Comment by MichaelGrupp** [comment]
Out of curiosity: for which particular scenarios was this designed?

**Comment by pifon2a** [comment]
To easily rerun the same bag several times.

**Comment by MichaelGrupp** [comment]
Ahh I see, thanks.

**Comment by gaschler** [comment]
Another scenario is when you want to reproduce timing as closely as possible.
I once needed it when I measured cartographer_ros' delay from incoming laser scan to tf publish.
It avoids the simulated clock, which has some milliseconds of jitter.

**Pull request merged**
