### PR TITLE
Remove unused variable from submaps_display.cc

### PR DESCRIPTION
**Pull request by MichaelGrupp**
Fixes a Clang compiler warning.

### CODE REVIEW

**Comment by cschuet** [comment]
@MichaelGrupp Thanks!

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Error: PUT https://api.github.com/repos/googlecartographer/cartographer_ros/pulls/840/merge: 405 At least 1 approving review is required by reviewers with write access. []

Log:
~~~
=> handle work item: PR 840 on googlecartographer/cartographer_ros.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer_ros]
HEAD is now at 0a91789 Add a launch and configuration file for writing a ROS map (#577) (#721)
 $ git clean -fd [data/cartographer_ros]
 $ git checkout master [data/cartographer_ros]
Already on 'master'
Your branch is up to date with 'origin/master'.
 $ git pull [data/cartographer_ros]
Already up to date.
 => Checking out magazino/fix-submap-display-clang as local branch pr_840.
 $ git remote add magazino git@github.com:magazino/cartographer_ros.git [data/cartographer_ros]
fatal: remote magazino already exists.
 $ git fetch magazino [data/cartographer_ros]
 $ git branch --track pr_840 magazino/fix-submap-display-clang [data/cartographer_ros]
Branch 'pr_840' set up to track remote branch 'fix-submap-display-clang' from 'magazino'.
 => Switching to branch pr_840.
 $ git reset --hard HEAD [data/cartographer_ros]
HEAD is now at 0a91789 Add a launch and configuration file for writing a ROS map (#577) (#721)
 $ git clean -fd [data/cartographer_ros]
 $ git checkout pr_840 [data/cartographer_ros]
Switched to branch 'pr_840'
Your branch is up to date with 'magazino/fix-submap-display-clang'.
 $ git pull --force [data/cartographer_ros]
Already up to date.
 => merge master.
 $ git merge master [data/cartographer_ros]
Already up to date.
 => Running clang-format on all *.cc and *.h files
 $ git commit -am Ran clang-format. [data/cartographer_ros]
On branch pr_840
Your branch is up to date with 'magazino/fix-submap-display-clang'.

nothing to commit, working tree clean
 $ git push --force magazino HEAD:fix-submap-display-clang [data/cartographer_ros]
Everything up-to-date
 => Abandoning branch pr_840.
 => Switching to branch master.
 $ git reset --hard HEAD [data/cartographer_ros]
HEAD is now at 9e209f2 Remove unused variable from submaps_display.cc
 $ git clean -fd [data/cartographer_ros]
 $ git checkout master [data/cartographer_ros]
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 $ git branch -D pr_840 [data/cartographer_ros]
Deleted branch pr_840 (was 9e209f2).

~~~

**Pull request merged**
