### PR TITLE
Use immediately invoked lambda for tracking_to_local.

### PR DESCRIPTION
**Pull request by MichaelGrupp**
Restores const-correctness that we dropped when introducing the 
`publish_frame_projected_to_2d` param without using a ternary operator.

### CODE REVIEW

**Comment by MichaelGrupp** [comment]
See https://herbsutter.com/2013/04/05/complex-initialization-for-a-const-variable/

**Comment by ojura** [comment]
This is awesome! Examples where this could be used are all over the codebase.

**Comment by MichaelGrupp** [comment]
@ojura Yes! Saw a presentation about this yesterday at a meet-up and immediately thought the same ;)

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by cschuet** [comment]
@MichaelGrupp Thanks!

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Pull request merged**
