### PR TITLE
Address some issues of the review

### PR DESCRIPTION
**Pull request by Mofef**
So far I didn't find the new way of doing `map_builder_.sparse_pose_graph()->GetSubmapTransforms`.
Hints are appreciated :)

### CODE REVIEW

**Comment by Mofef** [comment]
Ouch... This was not what I had in mind... Is there a way to push to an open PR?

**Comment by ojura** [comment]
You can submit a pull request for my fork - just select my fork as the base fork when creating a pull request. Actually, I have already addressed these smaller issues by Wohe, just forgot to push it - sorry, now you did some double work :) I have merged most of the changes, except the lines where you still use GetSubmapTransforms - I am planning to look into the new API and see how this should be replaced.

**Comment by ojura** [comment]
BTW, this is how you would create a pull request for my fork:

**Comment by Mofef** [comment]
That's what I thought, but it doesn't offer to choose your fork...?
screenshot from 2017-06-29 11-13-29

**Comment by ojura** [comment]
That is very odd. Maybe this link will work for you?
https://github.com/larics/cartographer_ros/compare/constraints_visualization...magazino:constraints_visualization

**Comment by Mofef** [comment]
it does work... very odd :/
Might be that its related to force pushes you did?

**Comment by Mofef** [comment]
Anyway for now I will file a ticket at Github and close this one

**Comment by ojura** [comment]
Yeah, sorry about that, I hoped you wouldn't notice these :D But I don't think it should be related. Probably a Javascript bug in your browser or on the Github page, which caused the list of available base repositories to be empty.

**Pull request closed without merging**
