### PR TITLE
Register internal metrics and provide a public interface.

### PR DESCRIPTION
**Pull request by MichaelGrupp**
[RFC 24](https://github.com/googlecartographer/rfcs/blob/master/text/0024-monitoring-ros.md)

Public API:
  - adds `cartographer_ros::metrics::FamilyFactory`
  - compatible with `::cartographer::metrics::RegisterAllMetrics`

Public RPC interface:
  - adds the ROS service `/read_metrics`
  - response contains the latest values of all available metric families

### CODE REVIEW

**Comment by MichaelGrupp** [comment]
Do you think the metrics should be optional? I.e. should we add an option `--collect_metrics=false` for the executables?

**Comment by cschuet** [comment]
@MichaelGrupp Thanks, adding a command-line option with default ```false``` sounds good to me.

**Comment by MichaelGrupp** [comment]
@cschuet Added the option. The service will return an `UNAIVALABLE` status code if it is not set.

**Comment by MichaelGrupp** [comment]
Done.

**Pull request merged**
