### PR TITLE
Use 'landmarks' instead of 'landmark'.

### PR DESCRIPTION
**Pull request by pifon2a**

### CODE REVIEW

**Comment by JiahengZhao** [comment]
Hi, I'm trying to use landmarks with cartographer, but I'm not sure about the format of landmarks in a ros bag. Could you please open source a ros bag with landmarks?

**Comment by mojovski** [comment]
Is there a new bag file with landmark demonstration?

**Comment by hobbyjobs** [comment]
Is there a new bag file with landmark demonstration?

**Comment by pifon2a** [comment]
@hobbyjobs you mean newer than this one: https://google-cartographer-ros.readthedocs.io/en/latest/demos.html#static-landmarks

**Pull request merged**
