### PR TITLE
Simultaneous trajectories bugfix: Do not forget to finish trajectory if last message is not from a sensor topic

### PR DESCRIPTION
**Pull request by ojura**
Bug introduced in #636.

### CODE REVIEW

**Comment by ojura** [comment]
@cschuet @gaschler this fixes a failed `CHECK` at the end for some bags. Sorry about that.

**Comment by ojura** [comment]
@cschuet can you please please merge this ASAP?

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 1.

**Pull request merged**
