### PR TITLE
Add finalize option in write state service.

### PR DESCRIPTION
**Pull request by jihoonl**
to support saving of fully optimized state without killing the cartographer node.

### CODE REVIEW

**Comment by cschuet** [comment]
Sorry we are having some troubles with our merge bot.

**Comment by cschuet** [comment]
Can you reupload this?

**Comment by jihoonl** [comment]
#613 is the same as this. I had to create new PR because I cannot reopen this.

**Comment by cschuet** [comment]
Thanks and sorry for the inconvenience.

**Pull request closed without merging**
