### PR TITLE
Update ROS API documentation with description of changed/new services

### PR DESCRIPTION
**Pull request by mgladkova**
Short description about new service /trajectory_query (#1222) and updated /start_trajectory (#1245).

### CODE REVIEW

**Comment by MarcelSoler** [comment]
Hello! 
I don't know If I'am asking in the proper place... But it's kind of related to the API and the documentation, so I'll ask it here.
I have a doubt regarding timestamp param of the initial_pose old service.

Testing with the old service I discovered that if I din't use {timestamp = 0 } the map coordinates didn't match my optimised trajectory https://github.com/googlecartographer/cartographer_ros/issues/913#issuecomment-483974223. Making the possibility of re-localising using the map coordinates impossible.

Reading https://github.com/googlecartographer/rfcs/blob/master/text/0028-simplify-ros-start-trajectory.md
I believe that you are taking about this parameter as keep time. And the conclusion of the discussion is that it won't be exposed in the ros service.

My question is how do I use the trajectory without optimisation (time 0 instead of current_time) without this param?  Is this taken into account in the refactor. If it is how can I use it properly?

Thank you!

**Comment by MichaelGrupp** [comment]
@MarcelSoler The timestamp argument doesn't need to be set over the ROS service call anymore (to prevent confusion). It is now implicitly set to 0 in the service handler: https://github.com/googlecartographer/cartographer_ros/commit/92a8b81a8489dd71a73c6d838c560712311b1da5#diff-e1f4eea55ec120f9e563c2b5d947449aR571

So you don't need to worry about that anymore.

**Comment by ojura** [comment]
Have you figured out what it does? :)

**Comment by MarcelSoler** [comment]
@MichaelGrupp  Nice! I was worried that was non zero by default. Looking forward to try it!

**Comment by MichaelGrupp** [comment]
@ojura The time is used to lookup an interpolated pose in the other trajectory, to which the relative pose is applied: see [here](https://github.com/googlecartographer/cartographer/blob/2adeb1f3beecf8427296ed2ff5a3e11925187521/cartographer/mapping/internal/2d/pose_graph_2d.cc#L1075). This means that:

* initial pose time == latest time -> relative pose is applied to end of other trajectory
* initial pose time == earliest time -> relative pose is applied to start of other trajectory (origin)
* somewhere in between -> relative pose is somewhere in between

Since the use cases for anything except the origin are probably rare (at least I don't come up with one), we just use the earliest time.

---

Moreover, the initial pose [updates the trajectory connectivity state](https://github.com/googlecartographer/cartographer/blob/2bd987ffb40e2d6667682c5c96432173f371094f/cartographer/mapping/internal/trajectory_connectivity_state.cc#L26) between the two trajectories in the pose graph - i.e. indicating that the two trajectories belong to the same disjoint set of connected trajectories. This speeds up constraint search.

**Comment by cschuet** [comment]
Thanks @mgladkova !

**Pull request merged**
