### PR TITLE
Fix race-condition when attempting to fetch trimmed submap slices.

### PR DESCRIPTION
**Pull request by MichaelGrupp**
A simple solution for a slightly more complex scenario:
- a pure localization trajectory `X` gets finished & trimmed in the main node
- at the same time, the occupancy_grid_node handles an outdated SubmapList
  message in which a submap ID `id` of trajectory `X` is still present
- the call to FetchSubmapTextures(`id`, ...) leads to a crash

With this fix, the trimmed submap IDs are just ignored until the next
iteration (in which the occupancy grid node removes the trimmed IDs).

### CODE REVIEW

**Comment by MichaelGrupp** [comment]
Noticed this while playing around with a new initial pose handler that finishes the current trajectory and starts a new one for each initial pose message from Rviz. I could reproduce this crash several times.

Please note that the error message `Requested submap 1 from trajectory 10 but it does not exist: maybe it has been trimmed.` is still logged once with the fix.

**Comment by cschuet** [comment]
@wally-the-cartographer merge

**Comment by cschuet** [comment]
@MichaelGrupp Thanks!

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user cschuet. Merge queue now has a length of 1.

**Pull request merged**
